name: mkdocs-asf-theme
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pip
  # For packaging and distribution
  - build
  - setuptools>=64
  - setuptools_scm>=8
  - mkdocs
  - mkdocs-material>=9.4.2,<10
